"use strict";
let decimal = 6;
console.log(decimal);
let hex = 0xf00d;
console.log(hex);
let binary = 0b1010;
console.log(binary);
let octal = 0o744;
console.log(octal);
let notANumber = NaN;
console.log(notANumber);
let underScoreNum = 1000000;
console.log(underScoreNum);
